### ISSUE TITLE
After installation: DEVEDENG menu: all entries are greyed out [Solution: use libavcodec56 from other repo]

### ISSUE THREAD

**Issue by Wikinaut** [rastersoft/devedeng#14]
After the initial installation, all menu entries are grey, and a DVD creation process cannot be started.

Pls. assist.

**Comment by rastersoft** [comment]
That is because your system lacks all the dependencies needed (like dvdauthor, ffmpeg, avconv...). Click the button in the bottom of the main window to see what you need to install.

**Comment by Wikinaut** [comment]
```
Movie identifiers (install at least one of these):

    MPLAYER (installed)
    FFPROBE (installed)
    AVPROBE (not installed)

Movie players (install at least one of these):

    VLC (installed)
    MPV (not installed)
    MPLAYER (installed)

Movie Converters (install at least one of these):

    FFMPEG () (installed)
    AVCONV () (not installed)

CD/DVD burners (install at least one of these):

    BRASERO (not installed)
    K3B (installed)

ISO creators (install at least one of these):

    MKISOFS (installed)
    GENISOIMAGE (installed)

Other programs:

    DVDAUTHOR (dvd) (installed)
    VCDIMAGER (vcd, svcd, cvd) (installed)
    SPUMUX (dvd, vcd, svcd, cvd) (installed)


```

**Comment by rastersoft** [comment]
Ops... That's odd...

**Comment by rastersoft** [comment]
Mmmm... The FFMPEG one has a problem: it doesn't specifies what kind of videos can create. Maybe you lack codecs...

**Comment by Wikinaut** [comment]
no, codecs are present. I run Opensuse Tumbleweed and have FFMPEG (is a beast) and the codecs from the PACKMAN repo.

Maybe your checks are too strict ?

**Comment by rastersoft** [comment]
Yes, it is probable... Unfortunately I use Debian, and can't use ffmpeg without compiling, so I can't do a fully test :(

**Comment by Wikinaut** [comment]
Where can I patch the code so that the checks are perhaps not preventing it from starting ?

**Comment by rastersoft** [comment]
In the "ffmpeg.py" file, in the "check_is_installed" method. But please, run "ffmpeg -codecs" and post the output.

**Comment by Wikinaut** [comment]
see http://dpaste.com/2CE9XE5

**Comment by rastersoft** [comment]
Mmmm... it seems you have something wrong in your system. Look:

 ..A.L. mp1                  MP1 (MPEG audio layer 1)
 ..A.L. mp2                  MP2 (MPEG audio layer 2)
 ..A.L. mp3                  MP3 (MPEG audio layer 3)

None of the three MPx audio layers are marked as Decoder or Encoder... Also, both H264, MPEG-1 and MPEG-2 video are marked only as decoder, but not encoder:

 D.V.L.  mpeg1video           MPEG-1 video
 D.V.L.  mpeg2video           MPEG-2 video
 D.V.LS h264                      H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10

This explains why Devede-NG refuses to allow to create videos :(

**Comment by glenntanner3** [comment]
We should try to include that in the log

**Comment by rastersoft** [comment]
The problem is that if ffmpeg doesn't allow to encode with MPEG-2, devede won't be able to create DVDs. The problem here is in FFMpeg, not in Devede.

**Comment by Wikinaut** [comment]
@rastersoft I understand, however, Devede should tell this to the user, perhaps also give hints how to solve (currently, it is silent about this problem of the dependency i.e. ffmpeg).

**Comment by glenntanner3** [comment]
It should, and I'm looking into that.

**Comment by rastersoft** [comment]
In fact, it is telling that: it shows nothing in the FFMPEG line. Compare yours with mine:

Conversores de películas (instalar al menos uno de éstos):

```
FFMPEG () (no instalado)
AVCONV (vcd, svcd, cvd, dvd, divx, mkv) (instalado)
```

As you can see, in mine (with AVConv) it tells that it is installed and can be used to generate video cd, super video cd, china video disc, DVD, DivX and Matroska files.

**Comment by Wikinaut** [comment]
output should then indicate

```
FFMPEG (vcd-, svcd-, cvd-, dvd-, divx-, mkv-)
xxx- indicates a missing but required codec
```

instead of being so silent ()

**Comment by Wikinaut** [comment]
After having contacted Opensuse experts, who informed me that ffmpeg is only a frontend and that the important stuff is done by libavcodec56, I decided to install libavcodec56 not from Opensuse Tumbleweed repo but from videolan.

This newer version comes with a lot of more coders, which are not only present but also **enabled**.

Devede now starts for me (I haven't created an ISO image so far, but close the issue now, because the "greyed-out" problem (this issue) is solved as such.
