### ISSUE TITLE
/usr/share/devede_ng/silence.ogg: Invalid data found when processing input

### ISSUE THREAD

**Issue by Wikinaut** [rastersoft/devedeng#15]
- version 41ca337a70a9e9bf446332c65fc6af5cc29b6f1c
- Merge: bf847b5 72815ec
- Author: Sergio Costas sergio.costas@rastersoft.com
- Date:   Fri Jul 3 22:23:39 2015 +0200

While trying to create a DVD, I got the following 
debug output

```
Creating menu 0

Launching: ffmpeg -loop 1 -f image2 -i /home/benutzer/Videos/production/movie/menu/menu_0_bg.png -i /usr/share/devede_ng/silence.ogg -y -target pal-dvd -acodec mp2 -s 720x576 -g 12 -b:v 2500k -b:a 224k -aspect 4:3 -t 31 /home/benutzer/Videos/production/movie/menu/menu_0.mpg

Converting Udo_Jürgens-_Udo_Jürgens_-_Mitten_im_Leben_-150708_konzert_udo_2256k_p14v11

Launching: ffmpeg -i /home/benutzer/Videos/MediathekView/Udo_Jürgens/Udo_Jürgens-_Udo_Jürgens_-_Mitten_im_Leben_-150708_konzert_udo_2256k_p14v11.mp4 -i /home/benutzer/Videos/MediathekView/Udo_Jürgens/Udo_Jürgens-_Udo_Jürgens_-_Mitten_im_Leben_-150708_konzert_udo_2256k_p14v11.mp4 -map 1:0 -map 0:1 -vf scale=720:576 -y -target pal-dvd -sn -g 12 -bf 2 -strict 1 -ac 2 -aspect 1.7777777777777777 -s 720x576 -trellis 1 -mbd 2 -b:a 224k -b:v 5000k /home/benutzer/Videos/production/movie/movies/movie_0
```

The first command run manually gives the error message:

```
# ffmpeg -loop 1 -f image2 -i /home/benutzer/Videos/production/movie/menu/menu_0_bg.png -i /usr/share/devede_ng/silence.ogg -y -target pal-dvd -acodec mp2 -s 720x576 -g 12 -b:v 2500k -b:a 224k -aspect 4:3 -t 31 /home/benutzer/Videos/production/movie/menu/menu_0.mpg
/usr/share/devede_ng/silence.ogg: Invalid data found when processing input
```

**Comment by glenntanner3** [comment]
Just for sanity check, can you LS the directory '/usr/share/devede_ng/'

**Comment by Wikinaut** [comment]
see http://dpaste.com/0T1592H

**Comment by glenntanner3** [comment]
Do you have ogg support? ffmpeg -formats | grep ogg

**Comment by glenntanner3** [comment]
@rastersoft please don't close if it is a missing codec. I want to include even this into the error messages.

**Comment by Wikinaut** [comment]
http://dpaste.com/1A4BSTG

(I continue to hate ffmpeg)

**Comment by glenntanner3** [comment]
You need to install vorbis (ogg) codec for your system. Please let this issue open as I want to add an error message saying the same. Why do you hate ffmpeg?

**Comment by rastersoft** [comment]
Mmmm... What's that "WARNING: library configuration mismatch"?

**Comment by Wikinaut** [comment]
Short version: I finally could create and burn a DVD.

Long version: 

Ok, thanks for pointing out the library issue. 

I solved that as follows on my Opensuse Tumbleweed system: 
- I removed all "vlc" code (which is known to often interfere with ffmpeg libraries).
- Then I made sure to have most of the libraries from the Tumbleweed repo with the same version number 2.7.1-1.2 (some libs still have 2.7.1-1.1 or 0.7.16-3.16, because no newer versions are available).

Now the devede menu shows all menu items in "black" (not "greyed") and I could successfully create and burn (with k3b) a DVD with a 10-minute movie (originally an mp4 file).

For your information: see http://dpaste.com/18KA2HC for output of
- ffmpeg -codec
- devede debug info

You can close the issue now, if you want.

**Comment by glenntanner3** [comment]
Good to hear, but like I said, I would like to keep it open as I want to further inform the user of things like this to prevent further issues.

**Comment by rastersoft** [comment]
Yes, that's why I didn't close it.

**Comment by rastersoft** [comment]
So...? Can I close this?

**Comment by Wikinaut** [comment]
(will check later. Please leave it open)

**Comment by rastersoft** [comment]
ok
