### ISSUE TITLE
DVD menu can't be set as 16:9

### ISSUE THREAD

**Issue by LouisDK1** [rastersoft/devedeng#21]
I would be really nice if Devede had a feature to select whatever you want an old school 4:3 DVD menu or the more common 16:9 DVD menu. I really miss this feature.

**Comment by rastersoft** [comment]
Hi:

The problem is that I don't know exactly how to instruct DVDAuthor to create a 16:9 dvd menu. If you know how to do it, I'll implement it.

**Comment by LouisDK1** [comment]
I know that software like DVDStyler can do it. Maybe they do it by defining weight and height of menu based upon the video format.

If this feature got implemented I ditch DVDStyler as your software is much simpler to use.

**Comment by pletiplot** [comment]
Either to fork  dvdauthor or alter the resulting config after creating.

**Comment by rastersoft** [comment]
Added experimental support in master branch. Please, check it out.

**Comment by orbea** [comment]
I tested this in the 4.11.0 release and it worked just fine. :)

**Comment by rastersoft** [comment]
Great!
