### ISSUE TITLE
ImportError: No module named 'devedeng.help'

### ISSUE THREAD

**Issue by jorgevasquezp** [rastersoft/devedeng#22]
I'm trying the program in my Arch Linux, and  I'm getting this error when trying to launch it :+1: 

Traceback (most recent call last):
  File "/usr/bin/devede_ng.py", line 27, in <module>
    import devedeng.project
  File "/usr/lib/python3.5/site-packages/devedeng/project.py", line 41, in <module>
    import devedeng.help
ImportError: No module named 'devedeng.help'

My python version in 3.5.0 Maybe that's the problem ?

**Comment by rastersoft** [comment]
Hi:

I presume that you downloaded the git repository. The problem was that I
forgot to include the help.py file. I added it just now.

Sorry.

El 28/10/15 a las 16:23, Jorge Vasquez Perez escribió:

> I'm trying the program in my Arch Linux, and I'm getting this error
> when trying to launch it :+1:
> 
> Traceback (most recent call last):
> File "/usr/bin/devede_ng.py", line 27, in
> import devedeng.project
> File "/usr/lib/python3.5/site-packages/devedeng/project.py", line 41, in
> import devedeng.help
> ImportError: No module named 'devedeng.help'
> 
> My python version in 3.5.0 Maybe that's the problem ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rastersoft/devedeng/issues/22.

## 

Nos leemos
                     RASTER      (Linux user #228804)
sergio.costas@rastersoft.com        http://www.rastersoft.com
