### ISSUE TITLE
Menu window doesn't fit screen

### ISSUE THREAD

**Issue by pepeleproso** [rastersoft/devedeng#29]
On my notebook, the menu window doesn't fit on screen at a resolution of 1366x768. I can't see Ok and cancel buttons nor resize that window.
I'm using gnome shell 3.18 and fedora 24 with lastest Git.

**Comment by rastersoft** [comment]
It should work fine now. Check it from Git. I'll upload packages to my home page as soon as I build them.

**Comment by pepeleproso** [comment]
Thanks!!  I will try it soon
