### ISSUE TITLE
Invaild option

### ISSUE THREAD

**Issue by Flare183** [rastersoft/devedeng#30]
After telling DeVeDe to encode my movie, it gives me an error saying something about memcoder, but when I try from the terminal it gives me this: 
Launching program:  ffmpeg -i /home/jesse/Videos/s-CRY-ed [ACX]/[ACX]s-CRY-ed_-_01_-_Kazuma_[octavarium]_[66DF45E4].mkv -vf scale=720:480,fifo,pad=720:480:0:0:0x000000 -y -target ntsc-dvd -acodec ac3 -sn -g 12 -bf 2 -strict 1 -ac 2 -s 720x480 -threads 4 -trellis 1 -mbd 2 -b 5018000 -ab 384000 -aspect 4:3 -pass 1 -passlogfile /home/jesse/Videos/Output/Disc1/movie/movie.log -y /dev/null -newaudio
elemento:  /usr/bin
ffmpeg version 2.8.5 Copyright (c) 2000-2016 the FFmpeg developers
  built with FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
  configuration: --prefix=/usr/local --mandir=/usr/local/man --datadir=/usr/local/share/ffmpeg --pkgconfigdir=/usr/local/libdata/pkgconfig --enable-shared --enable-gpl --enable-postproc --enable-avfilter --enable-avresample --enable-pthreads --disable-libstagefright-h264 --disable-libutvideo --disable-libsoxr --cc=cc --extra-cflags='-I/usr/local/include/vorbis -I/usr/local/include' --extra-ldflags='-L/usr/local/lib ' --extra-libs=-lpthread --disable-libaacplus --disable-indev=alsa --disable-outdev=alsa --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libass --disable-libbs2b --disable-libcaca --disable-libcdio --disable-libcelt --disable-libdc1394 --disable-debug --enable-htmlpages --disable-libfaac --disable-libfdk-aac --enable-ffserver --disable-libflite --enable-fontconfig --enable-libfreetype --enable-frei0r --disable-libfribidi --disable-libgme --disable-libgsm --enable-iconv --disable-libilbc --disable-indev=jack --disable-ladspa --disable-libmp3lame --disable-libbluray --disable-mmx --disable-libmodplug --disable-openal --disable-indev=openal --disable-opencl --enable-libopencv --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-libopus --disable-libpulse --disable-indev=pulse --disable-outdev=pulse --disable-libquvi --enable-runtime-cpudetect --disable-librtmp --enable-libschroedinger --disable-ffplay --disable-outdev=sdl --disable-libsmbclient --disable-libsnappy --disable-libspeex --disable-sse --disable-libssh --enable-libtheora --disable-libtwolame --disable-libv4l2 --disable-indev=v4l2 --disable-outdev=v4l2 --disable-vaapi --disable-vdpau --disable-libvidstab --enable-libvorbis --disable-libvo-aacenc --disable-libvo-amrwbenc --enable-libvpx --disable-libwavpack --disable-libwebp --disable-x11grab --enable-libx264 --disable-libx265 --disable-libxcb --enable-libxvid --disable-outdev=xv --disable-libzmq --disable-libzvbi --enable-gnutls --disable-openssl --disable-version3 --disable-nonfree
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
Unrecognized option 'newaudio'.
Error splitting the argument list: Option not found
Creating window /usr/local/share/devede/werror_dialog.ui

**Comment by rastersoft** [comment]
What is your linux distribution, please? Which version of Devede are you using?
