### ISSUE TITLE
Allow using growisofs as dvd burner?

### ISSUE THREAD

**Issue by orbea** [rastersoft/devedeng#31]
Is it possible that growisofs can be used as a backend for burning dvds?

Since I do not want to use k3b or brasero, I found I can use growisofs to burn the iso created by devedeng to a blank dvd manually which works well.

```
growisofs -dvd-compat -Z /dev/sr1=movie.iso
```

I think dvd+rw-tools will be lighter and more accessible dependency than the current two.

**Comment by nick87720z** [comment]
Those two are already frontends for lowlevel things like growisofs and may be others (usually using libs). Using it directly will need more options, begining with at least device selection, and probably more.

Alternative for those, prefering such option, could be "Custom" option, to specify command with all options, substututing image file name, e.g. as %f.

**Comment by orbea** [comment]
I'm fine if this is not implemented and can continue using manually. I made this issue mostly to document the workaround since both k3b and brasero are highly undesirable for me because of their dependencies.

**Comment by rastersoft** [comment]
As commented, I didn't add growisofs direct support precisely because it needs some "low level data" like the device where the burner is and more, and Devede aims to be an easy-to-use program.
