### ISSUE TITLE
mkisofs output parsing can fail depending on locale

### ISSUE THREAD

**Issue by voyageur** [rastersoft/devedeng#38]
Environment: Gentoo 64-bit, cdrtools-3.02_alpha06, devedeng 4.6.1, "fr_FR.UTF-8" locale

With this environment, mkisofs verbose output is (notice the "," decimal separator)

<pre>  0,27% done, estimate finish Wed Apr  6 14:20:03 2016</pre>

This causes:

<pre>Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/devedeng/executor.py", line 295, in read_stderr
    self.process_stderr(final_data)
  File "/usr/lib64/python3.4/site-packages/devedeng/mkisofs.py", line 79, in process_stderr
    p = float(l[0])
ValueError: could not convert string to float: '  0,27'</pre>

A workaround is to force LC_NUMERIC=C

Possible fixes:
- use the locale module to parse the value with "setlocale(LC_NUMERIC, '')" and atof()
- Set LC_NUMERIC=C before running mkisofs subprocess
- Run console-only commands in full C locale (the first 2 fixes could break again if mkisofs output gets localized one day)

**Comment by timeraider4u** [comment]
I can confirm this bug on a workstation with German keyboard layout/timezone/etc. This bug is still present in DevedeNG-4.8.6.

**Comment by rastersoft** [comment]
Ops... sorry, this was accidentally kept in the queue... Merged.

**Comment by landscape69** [comment]
please release a new version with this fix. this bug make it completely useless at the moment.

thanks

p.s.: as i see u are using gentoo to, can u make also a live ebuild for devedeng please?

**Comment by rastersoft** [comment]
It is already merged. I will launch the packages now.

**Comment by megathlon** [comment]
Thanks for fixing this issue. The same bug is also present in genisoimage.py.
I'm not familiar with git and don't know how to submit a fix for that. Should I create a new issue so that someone else (e.g. timeraider4u) will have a look?

**Comment by rastersoft** [comment]
Fixed here, in the repo. In a couple of days I'll upload new packages to my home page. Thanks!

**Comment by megathlon** [comment]
Perfect. Thanks!
