### ISSUE TITLE
Saving Project - valueerror: row sequence

### ISSUE THREAD

**Issue by RecursiveProgrammer** [rastersoft/devedeng#47]
Linux Desk 4.8.8-2-ARCH #1 SMP PREEMPT Thu Nov 17 14:51:03 CET 2016 x86_64 GNU/Linux
Python 3.5.2

----

* Open devede_ng
* Select *DVD* option
* File -> Save
* File -> Open
* Success (no errors)
* Add a movie
* File -> Save
* File -> Open
* Error happens on the terminal and the file is not loaded.

Software version: 4.8.4

Error:

```
(devede_ng.py:1480): Gtk-WARNING **: Content added to the action area of a dialog using header bars
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/devedeng/project.py", line 685, in on_load_activate
    self.load_project(retval)
  File "/usr/lib/python3.5/site-packages/devedeng/project.py", line 732, in load_project
    self.wliststore_files.append([new_file, new_file.title_name,True,self.duration_to_string(new_file.get_duration())])
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gtk.py", line 956, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gtk.py", line 947, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gtk.py", line 849, in _convert_row
    raise ValueError('row sequence has the incorrect number of elements')
ValueError: row sequence has the incorrect number of elements
```

 Another error was happening when file->save action was being performed:

```
(devede_ng.py:10782): Gtk-WARNING **: Content added to the action area of a dialog using header bars
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

**Comment by RecursiveProgrammer** [comment]
Woot! I may have fixed it.

I just need to find out the dance to make the change: line 736, append: `,new_file.show_in_menu` as the last element in the array.

**Comment by RecursiveProgrammer** [comment]
Eh, My line number was wrong, Anyway, I did not see how to make a new branch (I am guessing it is disabled). I am uploading a .patch file to be merged in to project.py.
[project.py.patch.txt](https://github.com/rastersoft/devedeng/files/605703/project.py.patch.txt)


Cheers!

**Comment by rastersoft** [comment]
You must fork the project in your own github account, clone it in your computer, make the changes you want, push them to your repository, and only then you can click the "propose merge" button.

**Comment by rastersoft** [comment]
Applied. Thanks!
