### ISSUE TITLE
request for a live ebuild for gentoo user

### ISSUE THREAD

**Issue by landscape69** [rastersoft/devedeng#52]
it would be nice to have an live ebuild for this nice software to get uptodate, even this is sometime buggy and need to fetch from git.

thanks

**Comment by rastersoft** [comment]
In my homepage there are arch linux ebuilds. Maybe they are similar? (I don't know)

**Comment by voyageur** [comment]
Added to the Gentoo tree (along with new 4.8.7):
https://gitweb.gentoo.org/repo/gentoo.git/commit/media-video/devedeng?id=b6027329966e372e704612a998907e058384532e
(I am the downstream maintainer)

**Comment by landscape69** [comment]
thanks you very much... its great if all work fine now.
