### ISSUE TITLE
Version of installed devede

### ISSUE THREAD

**Issue by pletiplot** [rastersoft/devedeng#54]
Helo,
I have installed devede-ng from the git using setup. Then I have installed another version from the deb package. When I run binary from /usr/local/bin, I get same "Version:" as I run it from /usr/bin. I have noticed it reads the version from `/usr/local/lib/python3.4/dist-packages/devedeng-*.egg-info`. Only if I remove all localy installed file (including the egg-info, it reads from `/usr/local/lib/python3.4/dist-packages/devedeng-*.egg-info` . Version just do not match the real version of the executable file.

**Comment by rastersoft** [comment]
Unfortunately that's a problem from python, not devede itself. You can't have both versions installed at the same time because they will interfere.

**Comment by pletiplot** [comment]
So I would like to see if there is some upgrade option in the setup.py, may be some previous version detection, but it is another issue.

**Comment by rastersoft** [comment]
If you manually installed a version, you must manually uninstall it before installing a packaged version.

**Comment by pletiplot** [comment]
I see. I would normally settle for one version, but I was debugging #50 . We can keep this closed.
