### ISSUE TITLE
How do I use it after installing it?

### ISSUE THREAD

**Issue by still-dreaming-1** [rastersoft/devedeng#55]
So I tried installing it by downloading the source code and running `sudo ./setup.py install`. Assuming it worked correctly, how do I run it?

**Comment by rastersoft** [comment]
You should have an icon in the menus... Of course, assuming that you are using Linux.

**Comment by still-dreaming-1** [comment]
Oh thanks, it is in the menu! I tried typing devede and devedeng from the terminal and looking for an executable or python file to run.
