### ISSUE TITLE
Menu music always 30 seconds long

### ISSUE THREAD

**Issue by JohnVeness** [rastersoft/devedeng#57]
I created a menu music WAV file that was 48 seconds long, but when I create the DVD it has been truncated to 30 seconds.

Looking in src/devedeng/dvd_menu.py I see the line "self.add_integer_adjustment("sound_length", 30)" which looks like there is supposed to be a way we can adjust the length. But there is no corresponding sound_length entry in data/interface/wmenu.ui so I guess it's hidden in the UI.

**Comment by JohnVeness** [comment]
I've been looking into this further. I see that the code attempts to find the length of the menu music file and use that length when creating the menu mpeg. But it always passes 30 to create_menu_mpeg.

When running devedeng.py from a command prompt I see:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/devedeng/dvd_menu.py", line 100, in update_music
    (video, audio, length) = film_analizer.analize_film_data(
AttributeError: 'ffprobe' object has no attribute 'analize_film_data'
```
Similar happens if I change the Preferences to use avprobe.

Looking in ffmpeg.py and avprobe.py, neither have a analize_film_data function. I tried to change the code in dvd_menu.py to use get_film_data instead but that didn't work (I think that function is for something else).

**Comment by orbea** [comment]
@rastersoft Would you mind taking a look at this issue? I think it could improve menus a lot. :)

**Comment by rastersoft** [comment]
I'll try to fix this during the weekend...

**Comment by rastersoft** [comment]
Fixed. I'm preparing the packages.

**Comment by orbea** [comment]
This also works here, thanks a lot!
