### ISSUE TITLE
Deprecated GTK commands

### ISSUE THREAD

**Issue by glenntanner3** [rastersoft/devedeng#6]
I was going to use Glade to fix, but it will give errors while opening but not while running 'verify'. Perhaps we can work together to get these resolved.

`$ ./devede_ng.py 
Version: 4.0
/home/glennt/GIT/devedeng/src/devedeng/project.py:57: Warning: The property GtkImageMenuItem:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wmain.ui"))
/home/glennt/GIT/devedeng/src/devedeng/project.py:57: Warning: The property GtkSettings:gtk-menu-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wmain.ui"))
/home/glennt/GIT/devedeng/src/devedeng/project.py:57: Warning: The property GtkAlignment:left-padding is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wmain.ui"))
/home/glennt/GIT/devedeng/src/devedeng/project.py:57: Warning: The property GtkButton:yalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wmain.ui"))
/home/glennt/GIT/devedeng/src/devedeng/project.py:57: Warning: The property GtkButton:xalign is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wmain.ui"))
/home/glennt/GIT/devedeng/src/devedeng/project.py:57: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wmain.ui"))
/home/glennt/GIT/devedeng/src/devedeng/choose_disc_type.py:33: Warning: The property GtkWindow:has-resize-grip is deprecated and shouldn't be used anymore. It will be removed in a future version.
  builder.add_from_file(os.path.join(self.config.glade,"wselect_disk.ui"))
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
/home/glennt/GIT/devedeng/src/devedeng/file_movie.py:419: Warning: The property GtkWidget:margin-left is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(os.path.join(self.config.glade,"wfile_properties.ui"))
/home/glennt/GIT/devedeng/src/devedeng/file_movie.py:419: Warning: The property GtkWidget:margin-right is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(os.path.join(self.config.glade,"wfile_properties.ui"))
/home/glennt/GIT/devedeng/src/devedeng/file_movie.py:419: Warning: The property GtkMisc:xpad is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(os.path.join(self.config.glade,"wfile_properties.ui"))
/home/glennt/GIT/devedeng/src/devedeng/file_movie.py:419: Warning: The property GtkImage:stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.builder.add_from_file(os.path.join(self.config.glade,"wfile_properties.ui"))
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.                                                                       
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.`

**Comment by rastersoft** [comment]
I'm working on it. Give me some extra time.

**Comment by glenntanner3** [comment]
No worries, i have not been able to spend the time on this that I wanted to either.

**Comment by rastersoft** [comment]
I think all has been fixed.
