### ISSUE TITLE
App name and icon are incorrect under Gnome Wayland session

### ISSUE THREAD

**Issue by glaubersm** [rastersoft/devedeng#60]
I use 4.8.9 on Arch, Gnome 3.26, Wayland session.
My screenshot shows the alt+tab menu.

![captura de tela de 2017-09-22 13-39-59](https://user-images.githubusercontent.com/15967631/30755130-d75170f6-9f9b-11e7-9b37-2006a6167081.png)

**Comment by glaubersm** [comment]
4.8.10 has the same bug.

**Comment by rastersoft** [comment]
Unfortunately I can't launch wayland in my debian system (don't know why, it worked fine some months ago), so I can't check this.

**Comment by glaubersm** [comment]
what about virtualbox?

**Comment by rastersoft** [comment]
I found how to fix it. I'll try to fix it this weekend.

**Comment by glaubersm** [comment]
Thank you very much.

**Comment by rastersoft** [comment]
Please, try to run this from a command line:

    sudo gtk-update-icon-cache

and tell me if that fixes the problem.

**Comment by glaubersm** [comment]
bug persists.

**Comment by rastersoft** [comment]
Mmmm... it also fails in Vala apps...

**Comment by rastersoft** [comment]
Fixed in master. I'm building the packages now.
