### ISSUE TITLE
Improve subtitles appearance

### ISSUE THREAD

**Issue by glaubersm** [rastersoft/devedeng#61]
Some letters are difficult to distinguish (in my screenshots, "d" letter) because fonts appearence is not good enough. Compare the subtitles shown in the screenshots below.

Smplayer plays the ISO file generated by devede ng
![smplayer devede iso](https://user-images.githubusercontent.com/15967631/30758979-ca596322-9faa-11e7-8eb6-5a57a4cf1731.png)

Smplayer plays the same video with external SRT subtitles (same subtitles file that I used to generate the ISO file with devede ng)
![smplayer external srt](https://user-images.githubusercontent.com/15967631/30759150-7870d724-9fab-11e7-9069-af4237aae423.png)

**Comment by rastersoft** [comment]
This has to do with Spumux, the program that devede uses to render the subtitles. You should fill a bug report for it.
