### ISSUE TITLE
Subtitles from SVCD are corrupted

### ISSUE THREAD

**Issue by glaubersm** [rastersoft/devedeng#62]
Devede NG 4.8.9 on Arch.

![svcd](https://user-images.githubusercontent.com/15967631/30775644-9641a634-a06e-11e7-975a-dbd2b7bd411c.png)

**Comment by rastersoft** [comment]
This seems to be a problem with spumux (the program used by Devede to embed the subtitles), not with Devede. You should fill a bug report with them.
