### ISSUE TITLE
Cannot start devede

### ISSUE THREAD

**Issue by arun-gurung** [rastersoft/devedeng#64]
This is the error message I get.

[root@macbook-air ~]# /bin/python3 /bin/devede_ng.py 
Traceback (most recent call last):
  File "/bin/devede_ng.py", line 20, in <module>
    import gi
  File "/usr/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by rastersoft** [comment]
That is a bug in gobject introspection module for python, not in devede. You should send a bug report to the gi maintainer.

**Comment by arun-gurung** [comment]
Just want to report that devede version 3.23 works on my system.

**Comment by rastersoft** [comment]
Current version is 4.8.11. You should update.
But I see that you are using a mac. Where did you download devede?

**Comment by arun-gurung** [comment]
I have CentOS 7 on my Macbook Air, and I have updated to the latest packages.

Now I don't remember which version it was, but it was quite new 4.x and I get the error with "gi" as described above.

I tried to install version 4.8.11, but the autogen.sh configure script complains about too old Glib. And if I try to install the latest Glib, I get problems so I will wait with it.

**Comment by rastersoft** [comment]
Anyway, this is clearly a bug in gobject introspection package, not in Devede. Version 3.x of Devede used Gtk2, which didn't rely on gobject introspection, while version 4.x uses Gtk3, which needs it.

You should report this bug to the maintainer of that package in CentOS, anyway. I can't fix it from Devede.

**Comment by arun-gurung** [comment]
I reinstalled the whole Python 3.6.5 from scratch with modules and now Devedeng starts properly.
