### ISSUE TITLE
Can't run after install

### ISSUE THREAD

**Issue by iArska** [rastersoft/devedeng#67]
I have Linux Mint 18.3 and tried to install "Package for Ubuntu xenial" deb, after that tried Git verson. Neither will start with command "devede" or "devedeng". Neither of them added a shortcut to menu. Anyway, Devede 4.4 works (I uninstalled it before NG), but I would try the newer version. What went wrong with it?

**Comment by rastersoft** [comment]
The git version is installed at /usr/local... while the contained in the .deb package goes into /usr. Try to fully remove the one at /usr/local... with:

    sudo rm -rf /usr/local/lib/python3.6/dist-packages/devedeng*
    sudo rm -rf /usr/local/devedeng

(but change "python3.6" with the right folder name)

**Comment by iArska** [comment]
Problem solved, menu icon appeared and it starts with command "devede_ng.py".
