### ISSUE TITLE
Installing from source on Devuan (similar to Debian Jessie) - devedeng.mo missing

### ISSUE THREAD

**Issue by thjwong** [rastersoft/devedeng#72]
I am running Devuan 1.0, which is similar to Debian Jessie (all without systemd). 
The repository has only devede so I decided to install from source.
After downloading the master.zip from github page, and unpacking it, the ./setup.py script encountered the following error message:

error: can't copy 'locale/ca/LC_MESSAGES/devedeng.mo': doesn't exist or not a regular file

I checked the folder under the extracted master folder, there is nothing in locale/ca/LC_MESSAGES/
Please let me know if it is an issue or this can be fixed in other ways.

(By the way, I am installing hoping to use the manually defined chapter markers feature; currently this feature is not offered by any maintained DVD authoring software in linux, while the now-unmaintained Bombono in the past offered such a feature)

Thanks for breaking us this useful tool.

**Comment by rastersoft** [comment]
You need to install the package "gettext", because there is the "msgfmt" binary that compiles the translated strings.

I will add a check in the setup.py file for this, because currently it just passes if it fails...
