### ISSUE TITLE
DevedeNG creates dvd image that confuses VLC player

### ISSUE THREAD

**Issue by sthenc** [rastersoft/devedeng#8]
Hi,

It's me again.

I am not 100% sure this is a bug but:

If the video/audio settings for the menu don't match the settings for the rest of the videos,
and I generate an .iso image like that, then if I play that disk file with vlc, vlc will get confused,
and stretch my video as if it was 16:9.

I think the problem was the resolution setting not being the same, because when I manually set all
videos to 720x576, the problem dissapeared.

By the way, I noticed that when I played the videos on disk, VLC detects 2 video and 2 audio streams with different codecs, and I also see that there are some empty .VOB files in the dvd-tree directory.
Is that supposed to be like that ? It doesn't really make sense to me...

**Comment by glenntanner3** [comment]
Are you using FFMPEG or AVCONV?
